### ISSUE TITLE
5.0.0 Checklist

### ISSUE THREAD

**Issue by Avaq** [fluture-js/Fluture#72]
* [x] Fix #71 (Merge #73)
* [x] Remove `Future.cast` (Merge #75)
* [x] Remove `Future.fromForkable` (Merge #75)
* [x] Fix argument order of `Future.and` (Merge #74)
* [x] Find the reason for, and fix the problem causing `unhandledRejection` before the unit tests run
